### ISSUE TITLE
Any Chance for some documentation?

### ISSUE THREAD

**Issue by shayneoneill** [andygeiss/ecs#9]
This looks like its a pretty comprehensive ECS,  but I'm kinda struggling to make heads and tails of it (I'm fairly new to Go). 

Any chance for some documentation for this little guy?

Cheers.

**Comment by andygeiss** [comment]
I've added an example: https://github.com/andygeiss/ecs/tree/master/example
Maybe it helps ;-)

Run it with "go run example/main.go"
